service: serverless-app
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
