service: ecommerce-serverless-app-new
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  #this is lambda functions that responsible of execution a piece of code
  createProduct:
    handler: handler.createProduct
    events:
      #http event
      - http:
          method: post
          path: products
  updateProduct:
    handler: handler.updateProduct
    events:
      - http:
          method: put 
          path: product/{id}
  deleteProduct:
    handler: handler.deleteProduct
    events:
      - http:
          method: delete 
          path: product/{id}

#CloudFormation Resource templates 
#-->congif for creating databasa in dynamoDB
resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: productsId
            AttributeType: S
        KeySchema:
          - AttributeName: productsId
            KeyType: HASH